M48
; DRILL file {KiCad 7.0.1} date Sat 13 May 2023 23:39:39 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-13T23:39:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X5.6362Y-3.2774
X5.8638Y-3.2774
T2
X5.15Y-4.15
X5.55Y-4.15
X5.95Y-4.15
X6.35Y-4.15
T3
X5.0Y-3.8
X5.0Y-4.5
X6.5Y-3.8
X6.5Y-4.5
T0
M30
